### ISSUE TITLE
practical suggestion for jet engine development

### ISSUE THREAD

**Issue by mrmprogramer** [Crocoblock/jet-style-manager#2]
Hello. I have a practical suggestion for jet engine development.
I use Metabox fields to introduce more information about products. But not all fields should appear on all product pages because they are not related to that product.
In my opinion, it should be possible to limit each field to a certain number of categories so that the same categories are displayed only on the product management page. This is the simplest solution, otherwise it can be done for the whole meta box.
OK! Now I have created a post meta box and put (Enable For) on (products).
Adding and excluding individual products is very troublesome. There are two solutions.
1. Each metafield can be restricted to a specific product category to include the products listed in that category.
2. Restrict the entire meta box to one or more specific categories, in which case the entire meta fields of that meta box will be limited to the products listed in that category.
Thanks

**Comment by Floydtm** [comment]
Hello. It seems to me that you made a mistake with the repository. You need to leave a request here https://github.com/Crocoblock/suggestions/issues/new/choose
